# Generated by Django 6.1.1 on 2026-09-05 20:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='GerenteRegional',
            fields=[
                ('id_gerente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Gerente regional',
                'verbose_name_plural': 'Gerentes regionales',
                'db_table': 'gerente_regional',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'db_table': 'ingrediente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('numero_comensales', models.PositiveIntegerField(default=1)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_por_comensal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
                'db_table': 'menu',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id_platillo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Platillo',
                'verbose_name_plural': 'Platillos',
                'db_table': 'platillo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='MenuPlatillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.menu')),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.platillo')),
            ],
            options={
                'verbose_name': 'Platillo del menú',
                'verbose_name_plural': 'Platillos del menú',
                'db_table': 'menu_platillo',
                'unique_together': {('menu', 'platillo', 'dia_semana')},
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='platillos',
            field=models.ManyToManyField(related_name='menus', through='Gestion.MenuPlatillo', to='Gestion.platillo'),
        ),
        migrations.CreateModel(
            name='PlatilloIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidad_medida', models.CharField(max_length=20)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.ingrediente')),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.platillo')),
            ],
            options={
                'verbose_name': 'Ingrediente del platillo',
                'verbose_name_plural': 'Ingredientes del platillo',
                'db_table': 'platillo_ingrediente',
                'unique_together': {('platillo', 'ingrediente')},
            },
        ),
        migrations.AddField(
            model_name='platillo',
            name='ingredientes',
            field=models.ManyToManyField(related_name='platillos', through='Gestion.PlatilloIngrediente', to='Gestion.ingrediente'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredientes', to='Gestion.proveedor'),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='Gestion.cliente')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='Gestion.menu')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitud',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='clientes',
            field=models.ManyToManyField(related_name='menus_solicitados', through='Gestion.Solicitud', to='Gestion.cliente'),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=150)),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='Gestion.gerenteregional', verbose_name='Gerente regional')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='Gestion.sucursal')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='Gestion.sucursal'),
        ),
    ]
