# Generated by Django 6.1 on 2026-09-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramo (kg)'), ('l', 'Litro (l)'), ('pza', 'Pieza (pza)')], max_length=3, verbose_name='unidad de medida')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costo unitario')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'ingrediente',
                'verbose_name_plural': 'ingredientes',
                'ordering': ['nombre'],
            },
        ),
    ]
