# Generated by Django 6.1.1 on 2026-09-11 19:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_alter_ingrediente_costo_unitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del platillo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ingrediente',
            options={},
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Costo unitario'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramo (kg)'), ('lt', 'Litro (lt)'), ('pz', 'Pieza (pz)'), ('g', 'Gramo (g)'), ('ml', 'Mililitro (ml)')], max_length=50, verbose_name='Unidad de medida'),
        ),
        migrations.CreateModel(
            name='IngredientePlatillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad requerida del ingrediente', max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Gestion.ingrediente')),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='Gestion.platillo')),
            ],
            options={
                'verbose_name': 'Ingrediente de platillo',
                'verbose_name_plural': 'Ingredientes de platillos',
                'unique_together': {('platillo', 'ingrediente')},
            },
        ),
    ]
