# Generated by Django 6.1 on 2026-09-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_platillo_alter_ingrediente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='equivalencia_pza',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cuántas unidades de la unidad base equivalen a 1 pieza. Ej. 0.060 si 1 huevo = 0.060 kg. Vacío si no aplica.', max_digits=10, null=True, verbose_name='Equivalencia por pieza'),
        ),
    ]
