# Generated by Django 6.1 on 2026-09-15 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_ingrediente_equivalencia_pza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del menú')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuPlatillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicion', to='Gestion.menu')),
                ('platillo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Gestion.platillo')),
            ],
            options={
                'verbose_name': 'Platillo de menú',
                'verbose_name_plural': 'Platillos de menú',
                'unique_together': {('menu', 'platillo')},
            },
        ),
    ]
