# Generated by Django 6.1.1 on 2026-09-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0005_menu_menuplatillo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuplatillo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='menuplatillo',
            name='tiempo',
            field=models.CharField(choices=[('Desayuno', 'Desayuno'), ('Comida', 'Comida'), ('Cena', 'Cena')], default='Comida', max_length=20, verbose_name='Tiempo de comida'),
        ),
        migrations.AlterUniqueTogether(
            name='menuplatillo',
            unique_together={('menu', 'platillo', 'tiempo')},
        ),
    ]
