# Generated by Django 6.1.1 on 2026-09-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0006_alter_menuplatillo_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='comensales_cena',
            field=models.PositiveIntegerField(default=0, verbose_name='Comensales Cena'),
        ),
        migrations.AddField(
            model_name='menu',
            name='comensales_comida',
            field=models.PositiveIntegerField(default=0, verbose_name='Comensales Comida'),
        ),
        migrations.AddField(
            model_name='menu',
            name='comensales_desayuno',
            field=models.PositiveIntegerField(default=0, verbose_name='Comensales Desayuno'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='equivalencia_pza',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Equivalencia por pieza'),
        ),
    ]
