# Generated by Django 6.1.1 on 2026-09-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0007_menu_comensales_cena_menu_comensales_comida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramo (kg)'), ('lt', 'Litro (lt)'), ('pz', 'Pieza (pz)'), ('g', 'Gramo (g)'), ('ml', 'Mililitro (ml)'), ('gal', 'Galón (gal)')], max_length=50, verbose_name='Unidad de medida'),
        ),
    ]
